/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package youtube;

import org.testng.annotations.*;

import io.github.bonigarcia.wdm.WebDriverManager;

import static org.testng.Assert.*;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class TestCases {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    WebDriver driver;

    @BeforeSuite(alwaysRun=true)
    public void launchbrowser(){
        WebDriverManager.chromedriver().setup();
        driver=new ChromeDriver();
        driver.get("https://www.youtube.com/");
        driver.manage().window().maximize();
    }

    @AfterSuite
    public void teardown(){
        driver.close();
        driver.quit();
    }
}
